on:
  workflow_dispatch:
  push:
    branches:
      - main

name: Build and deploy to Docker Hub

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: c4stus/lights-api
        tags: type=sha

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        platforms: |
          linux/amd64
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Deploy to ArgoCD
      run: |
        set -e
        status_code=$(curl -o ./curl-request -w "%{response_code}" -X POST https://api.github.com/repos/castus/lights-api-charts/dispatches \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -u ${{ secrets.CHARTS_DEPLOY_TOKEN }} \
        --data '{"event_type": "deploy", "client_payload": { "image_tag": "'"${{ steps.meta.outputs.tags }}"'" }}')
        cat ./curl-request

        if [[ $status_code -eq 200 ]]; then
          echo "Request send"
        else
          exit 1
        fi
